# Assignment 2 - Numpy Array Operations


## Lets learn how Numpy operates


Numpy Operations and functions

NumPy is a library that helps us with the computation of the numerical data. With the help of NumPy, we read CSV files use methods like sum etc to be able to analyze our data and draw valuable insights. Let's have a look at some of the functions in NumPy and how they help us 

- arange
- numpy.split
- numpy.reshape
- numpy.all
- numpy.lib.scimath.power

In [1]:
import jovian

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [2]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = arange
function2 = split
function3 = reshape
function4 = all
function5 = lib.scimath.power

## Function 1 - arange 

Return evenly spaced values within a given interval.

In [3]:
# Example 1 - numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)¶
np.arange(3)

array([0, 1, 2])

With np.arange you need to provide the start number, the end number and the step count between the end and the start numbers. If you fail to provide the start number, numpy will take 0 as the default start value and will throw out the arrays as shown in above example.

In [4]:
# Example 2 - 
np.arange(10,110,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

As mentioned earlier, you can see NumPy has created an array with the gap of 10 between the numbers 10 and 110.

## Function 2 - split

Split an array into multiple sub-arrays as views into ary.

In [5]:
# Example 1 -
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

We saw in the earlier example of arange function where if we write a number within brackets, NumPy will create an array from the default value and then for the split function, it splits then into 3 arrays.

In [6]:
# Example 2 - 
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

Remember NumPy won't split the arrays into equal arrays. You can read more on the numpy.split by clicking on the link https://numpy.org/doc/stable/reference/generated/numpy.split.html#numpy.split

## Function 3 - reshape

Gives a new shape to an array without changing its data. If you wants your rows to be used as columns just use the reshape function.

In [7]:
# Example 1 - 
days = np.array([[1,2],
                 [3,4],
                 [5,6]])
days.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

Using the reshape function one could change the shape of the NumPy arrays that we create which will then in turn might be useful to perform another NumPy functions on.

In [8]:
# Example 2 - 
a = np.array([[1,2,3], [4,5,6]])

In [9]:
a.shape

(2, 3)

In [10]:
a.reshape((6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [11]:
a.reshape((6,1)).shape

(6, 1)

## Function 4 - all

Test whether all array elements along a given axis evaluate to True. Not a Number (NaN), positive infinity and negative infinity evaluate to True because these are not equal to zero.



In [12]:
# Example 1 - 
np.all([[True,False],[True,True]])

False

In [13]:
# Example 2 - 
np.all([-1, 4, 5])

True

## Function 5 - numpy.lib.scimath.power

Return x to the power p, (x**p) where p is the power to the x.

In [14]:
# Example 1 - 
np.lib.scimath.power([2, 4], 2)

array([ 4, 16])

2 and 4 are the numbers for which we would like to find the power of and 2 after the square brackets is the power so that leaves us with 4 and 16

In [15]:
# Example 2 - 
np.lib.scimath.power([a], 3)

array([[[  1,   8,  27],
        [ 64, 125, 216]]])

We can also pass a NumPy array in the function and it would return the numbers after applying the power to all the elements in the NumPy array created earlier.

## Conclusion

We took a look at split function that splits the arrays, we got to learn how simple it is for us if we want to create a numpy array within a certain number range and we also had a glance at the reshape function that allows us to reshape an array which then later helps us to perform any functions on the given array. These are few functions that we had discussed. Feel free to head over to the links given below and explore as much as possible to understand how powerful NumPy is with these functions.

## Reference Links
Refer to the links for references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Read more on the Numpy functions here : https://numpy.org/doc/stable/reference/routines.html
* Click the link to find the union two NumPy arrays https://www.geeksforgeeks.org/find-the-union-of-two-numpy-arrays/?ref=gcse

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>