Convert string to a number

In [9]:
def convert(num):
    return int(num)

Write a code snippet to convert a string to a list.

In [10]:
def s_to_l(string):
    return list(string.split(" "))

In [11]:
str1 = "Daksh Bhatnagar"
s_to_l(str1)


['Daksh', 'Bhatnagar']

Reverse the string

In [12]:
#Using indexing
str1[::-1]

'ragantahB hskaD'

In [13]:
#writing a custom function
def reverse(string):
    text_string = list(string)
    length = len(string)
    for i in range(length//2):
        text_string[i], text_string[length - i - 1 ] = text_string[length -  i - 1], text_string[i]
    return "".join(text_string)

In [14]:
name =  'Ayodhya Apts'
reverse(name)

'stpA ayhdoyA'

Sort a list

In [15]:
arr1  = [12,3,4,5,6,1,2,7,8,9]
sorted(arr1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 12]

How to access an element in a list

In [16]:
arr2 =  [[1,2,3,4,5], [5,4,3,2,1]]
arr2

[[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]]

In [17]:
#In 2d array we first access the row then the element, arr2[0] gives us the first row and then we can get 5 as per usual
arr2[0]

[1, 2, 3, 4, 5]

In [18]:
arr2[0][-1]

5

In [19]:
#Accessing the 1st value of the 2nd row
arr2[1][1]

4

In [20]:
arr1

[12, 3, 4, 5, 6, 1, 2, 7, 8, 9]

In [21]:
#remove takes the value in an array
arr1.remove(12)

In [22]:
arr1

[3, 4, 5, 6, 1, 2, 7, 8, 9]

In [23]:
#pop takes the index of the element in an array
arr1.pop(-1)

9

In [24]:
arr1

[3, 4, 5, 6, 1, 2, 7, 8]

Delete an entire List

In [25]:
arr1.clear()

In [26]:
arr1

[]

Reverse an array

In [27]:
# We will take 2 approaches, first is using a function and second one is without using a function
import numpy as np

In [28]:
np.flip(arr2) #reversiing 2d array, Notice only the elements have reversed, not the sub-elements

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [29]:
arr1  = [12,3,4,5,6,1,2,7,8,9]
np.flip(arr1)

array([ 9,  8,  7,  2,  1,  6,  5,  4,  3, 12])

In [30]:
#without using any function
arr1[::-1]

[9, 8, 7, 2, 1, 6, 5, 4, 3, 12]

Write a code snippet to get an element, delete an element, and update an element in an array.

In [31]:
##access an element
arr1[4]

6

In [32]:
#Remove an element
arr1.remove(2)

In [33]:
#Update an element
arr1[0]  = 100

In [34]:
arr1

[100, 3, 4, 5, 6, 1, 7, 8, 9]

In [35]:
arr1

[100, 3, 4, 5, 6, 1, 7, 8, 9]

Concatenate two different string lists

In [36]:
List1= ["W", "a", "w","b"]
List2 = ["e", " ","riting","log"]

In [37]:
List1 + List2

['W', 'a', 'w', 'b', 'e', ' ', 'riting', 'log']

Get the square of all the elements in a list

In [38]:
arr1

[100, 3, 4, 5, 6, 1, 7, 8, 9]

In [39]:
#Using Vanilla Python
[i**2 for i in arr1]

[10000, 9, 16, 25, 36, 1, 49, 64, 81]

In [40]:
#Using numpy
np.square(arr1)

array([10000,     9,    16,    25,    36,     1,    49,    64,    81])

Write a code to get the minimum value in a dictionary.


In [41]:
arr3 = [1,2,2,3,3,3,3,3,4,4,5,6,6,6,6,7,7,7,8,8,9,9]
dict1 = {i : arr3.count(i) for i in set(arr3)}

In [42]:
MIN_VALUE_TUPLE = min(dict1.items(), key=lambda x : x[-1])
MIN_VALUE_TUPLE

(1, 1)

In [43]:
a = np.array([[10, 4], [8, 12]])
b = np.array([[15, 6]])
np.concatenate([a,b])

array([[10,  4],
       [ 8, 12],
       [15,  6]])

If youb want to add a new column, reshape the array that's to be concatenated and specify `axis = 1` in the second argument of the `np.concatenate`

In [47]:
a = np.array([[10, 4], [8, 12]])
b = np.array([[15, 6]])
np.concatenate([a,b.reshape(-1,1)], axis=1)

array([[10,  4, 15],
       [ 8, 12,  6]])

Write code to insert commas between characters of all elements in an array

In [49]:
name

'Ayodhya Apts'

In [50]:
",".join(name)

'A,y,o,d,h,y,a, ,A,p,t,s'

How can you add 1 to all sides of an existing array?

In [51]:
arr2

[[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]]

In [54]:
np.pad(arr2, pad_width=1, mode='constant', constant_values=1)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 2, 3, 4, 5, 1],
       [1, 5, 4, 3, 2, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [53]:
np.pad(arr2, pad_width=2, mode='constant', constant_values=1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 2, 3, 4, 5, 1, 1],
       [1, 1, 5, 4, 3, 2, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [56]:
np.array(arr2).argsort()

array([[0, 1, 2, 3, 4],
       [4, 3, 2, 1, 0]])

In [57]:
arr2

[[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]]

In [58]:
import mysql.connector
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
conn =  mysql.connector.connect(host='localhost', user = 'root', database ='qssglobal', password = 'LfTu#Nw479')
cursor =  conn.cursor()

In [59]:
def read_sql(query):
    cursor.execute(query)
    results =  cursor.fetchall()
    df =  pd.DataFrame(results, columns = [i[0] for i in cursor.description])
    return df

In [61]:
df = read_sql("select * from dailydata")

Loc and iloc are two methods in pandas that work the same way until and unless there is a multi-index dataframe. For a multi-index dataframe you can just say `df.loc['index']` and then it return the corresponding values of the index.

In [67]:
df.iloc[0]

Status            L1 Rejected
Recruiter               Sajia
Date               2024-04-01
Qtr                        Q1
Month                     Apr
Client                Nerofix
KAM                     Sajia
CandidateName    Gaurav Tayde
Position            ASM- Pune
Year                     2024
Name: 0, dtype: object

How do you sort values of a dataframe?

In [68]:
df.sort_values('Date', ascending=False)

Status  Recruiter        Date Qtr Month   Client     KAM  \
2040  Shared With Client  Aishwarya  2024-05-04  Q1   May   Kubota   Rekha   
1026  Shared With Client      Kiran  2024-05-04  Q1   May  Nerolac   Sajia   
535   Shared With Client     Jahnvi  2024-05-04  Q1   May  Nerolac   Sajia   
536   Shared With Client     Jahnvi  2024-05-04  Q1   May  Nerolac   Sajia   
537   Shared With Client     Jahnvi  2024-05-04  Q1   May  Nerolac   Sajia   
...                  ...        ...         ...  ..   ...      ...     ...   
1036  Shared With Client     Pragya  2024-04-01  Q1   Apr      NTT  Pragya   
1037        L1 Scheduled     Pragya  2024-04-01  Q1   Apr      NTT  Pragya   
1038  Shared With Client     Pragya  2024-04-01  Q1   Apr      NTT  Pragya   
1039  Shared With Client     Pragya  2024-04-01  Q1   Apr      NTT  Pragya   
0            L1 Rejected      Sajia  2024-04-01  Q1   Apr  Nerofix   Sajia   

                  CandidateName              Position  Year  
2040          Sai Kumar Maddala     Material Planning  2024  
1026             Jaspreet Singh       TSO - Faridabad  2024  
535           Ritesh Srivastava          TSO Varanasi  2024  
536                 Madan Gopal          TSO Varanasi  2024  
537                 Sandeep Pal          TSO Varanasi  2024  
...                         ...                   ...   ...  
1036                  Radhika M  SOC Security Analyst  2024  
1037  Datla Surya Sudheer Varma  SOC Security Analyst  2024  
1038         G Sai Jogesh Varma  SOC Security Analyst  2024  
1039      Vamsi Krishna Reddy K  SOC Security Analyst  2024  
0                  Gaurav Tayde             ASM- Pune  2024  

[2041 rows x 10 columns]

Sorting the dataframe by 2 columns

In [69]:
df.sort_values(['Date', 'Recruiter'], ascending=False)

Status Recruiter        Date Qtr Month     Client     KAM  \
539   Shared With Client    Miloni  2024-05-04  Q1   May    Nerolac   Sajia   
540   Shared With Client    Miloni  2024-05-04  Q1   May    Nerolac   Sajia   
1024  Shared With Client     Kiran  2024-05-04  Q1   May    Nerolac   Sajia   
1025  Shared With Client     Kiran  2024-05-04  Q1   May    Nerolac   Sajia   
1026  Shared With Client     Kiran  2024-05-04  Q1   May    Nerolac   Sajia   
...                  ...       ...         ...  ..   ...        ...     ...   
770   Shared With Client   Alankar  2024-04-01  Q1   Apr  Honeywell  Deepak   
771          Hold by KAM   Alankar  2024-04-01  Q1   Apr  Honeywell  Deepak   
1287  Shared With Client      Ajaz  2024-04-01  Q1   Apr      Dinex    Giri   
1288  Shared With Client      Ajaz  2024-04-01  Q1   Apr      Dinex    Giri   
1723  Shared With Client    Aastha  2024-04-01  Q1   Apr     Kubota   Rekha   

        CandidateName         Position  Year  
539      Sushil Saini         TSO Agra  2024  
540       Vipul Kumar     TSO Varanasi  2024  
1024     Anshul Kumar  PSO - Ghaziabad  2024  
1025     Keshav Kumar  PSO - Ghaziabad  2024  
1026   Jaspreet Singh  TSO - Faridabad  2024  
...               ...              ...   ...  
770      Sunnit Nayak       ASM- Delhi  2024  
771   Amarendra Singh       ASM- Delhi  2024  
1287    LIBIN DHAS. C    Batch Process  2024  
1288     RAMANATHAN M    Batch Process  2024  
1723        Divakar R    TSM - Madurai  2024  

[2041 rows x 10 columns]

How to get the max value of a column and the index of that value?

In [73]:
max_val , max_index = df['Date'].max(), df['Date'].idxmax()

535

How can you split a column which contains strings into multiple columns?

In [82]:
df['Position'].str.split(pat=" ", expand=True)

0            1          2     3        4           5     6   \
0          ASM-         Pune       None  None     None        None  None   
1          ASM-         Pune       None  None     None        None  None   
2          ASM-         Pune       None  None     None        None  None   
3          ASM-         Pune       None  None     None        None  None   
4          ASM-         Pune       None  None     None        None  None   
...         ...          ...        ...   ...      ...         ...   ...   
2036        Sr.  Engineering    Manager  None     None        None  None   
2037        Sr.  Engineering    Manager  None     None        None  None   
2038  Assistant      Manager  Marketing     &  Product  Management  None   
2039  Assistant      Manager  Marketing     &  Product  Management  None   
2040   Material     Planning       None  None     None        None  None   

        7     8     9     10  
0     None  None  None  None  
1     None  None  None  None  
2     None  None  None  None  
3     None  None  None  None  
4     None  None  None  None  
...    ...   ...   ...   ...  
2036  None  None  None  None  
2037  None  None  None  None  
2038  None  None  None  None  
2039  None  None  None  None  
2040  None  None  None  None  

[2041 rows x 11 columns]

In [83]:
df

Status  Recruiter        Date Qtr Month   Client    KAM  \
0            L1 Rejected      Sajia  2024-04-01  Q1   Apr  Nerofix  Sajia   
1               Selected      Sajia  2024-04-01  Q1   Apr  Nerofix  Sajia   
2            L2 Rejected      Sajia  2024-04-01  Q1   Apr  Nerofix  Sajia   
3            L2 Rejected      Sajia  2024-04-01  Q1   Apr  Nerofix  Sajia   
4            L2 Rejected      Sajia  2024-04-01  Q1   Apr  Nerofix  Sajia   
...                  ...        ...         ...  ..   ...      ...    ...   
2036  Shared With Client      Divya  2024-05-04  Q1   May   Kubota  Rekha   
2037  Shared With Client      Divya  2024-05-04  Q1   May   Kubota  Rekha   
2038  Shared With Client  Aishwarya  2024-05-04  Q1   May   Kubota  Rekha   
2039  Shared With Client  Aishwarya  2024-05-04  Q1   May   Kubota  Rekha   
2040  Shared With Client  Aishwarya  2024-05-04  Q1   May   Kubota  Rekha   

                 CandidateName  \
0                 Gaurav Tayde   
1                Deepak Kakade   
2     Rupesh Dasharath Mangale   
3                  Rana Ranjit   
4                Sainath Bonde   
...                        ...   
2036            Surender Kumar   
2037           Santosh Shivaji   
2038          Aditya Bhadauria   
2039               Abhinav Lal   
2040         Sai Kumar Maddala   

                                              Position  Year  
0                                            ASM- Pune  2024  
1                                            ASM- Pune  2024  
2                                            ASM- Pune  2024  
3                                            ASM- Pune  2024  
4                                            ASM- Pune  2024  
...                                                ...   ...  
2036                           Sr. Engineering Manager  2024  
2037                           Sr. Engineering Manager  2024  
2038  Assistant Manager Marketing & Product Management  2024  
2039  Assistant Manager Marketing & Product Management  2024  
2040                                 Material Planning  2024  

[2041 rows x 10 columns]

In [85]:
query = '''
with cte as (select JoiningMonth, sum(case when JoiningStatus = 'Joined' then 1 else 0 end) as JoinedCount,
        sum(case when JoiningStatus = 'Joined' then Billable else 0 end) as JoinedBillable

from selections_23 where JoiningMonth in ('Apr', 'May', 'Jun') and JoiningYear = 2023
group by JoiningMonth
order by 
case when JoiningMonth = 'Apr' then 1
when JoiningMonth = 'May' then 2
when JoiningMonth = 'Jun' then 3
end),
cte_2023 as (select JoiningMonth, sum(case when JoiningStatus = 'Joined' then 1 else 0 end) as JoinedCount,
        sum(case when JoiningStatus = 'Joined' then Billable else 0 end) as JoinedBillable

from selections where JoiningMonth in ('Apr', 'May', 'Jun') and JoiningYear = 2024
group by JoiningMonth
order by 
case when JoiningMonth = 'Apr' then 1
when JoiningMonth = 'May' then 2
when JoiningMonth = 'Jun' then 3
end)


select t1.JoiningMonth, t1.JoinedCount as Joined_2023, t2.JoinedCount as Joined_2024, t1.JoinedBillable  as Billable_2023,
t2.JoinedBillable as Billable_2024 from cte t1 join cte_2023 t2 on t1.JoiningMonth =  t2.JoiningMonth 

'''
temp = read_sql(query)

In [87]:
temp

JoiningMonth Joined_2023 Joined_2024 Billable_2023 Billable_2024
0          Apr          24          35    2052030.00    3581900.00
1          May          33           4    2730580.00     399840.00
2          Jun          28           0    2993760.00          0.00

In [95]:
cols = list(temp.columns[1:])
for i in cols:
    temp[i] =  pd.to_numeric(temp[i])

How can you get the unique values and their count in an array. Also convert them to a dictionary and sort the dictionary by values highest to lowest

In [118]:
names, counts = np.unique(df['Recruiter'].values, return_counts=True)

In [123]:
counts_dict = sorted(dict(zip(names, counts)).items(), key=lambda x: x[-1], reverse=True)

In [124]:
counts_dict

[('Aishwarya', 106),
 ('Alankar', 95),
 ('Divya', 90),
 ('Rahul', 85),
 ('Nisha', 83),
 ('Pragya', 83),
 ('Ashutosh', 80),
 ('Miloni', 75),
 ('Kiran', 74),
 ('Sourav', 70),
 ('Prajnya', 69),
 ('Swati', 69),
 ('Aastha', 68),
 ('Ashad', 68),
 ('Ritu S', 68),
 ('Amit', 65),
 ('Jahnvi', 64),
 ('Kamal', 64),
 ('Damini', 63),
 ('Rakshita', 60),
 ('Aryan', 59),
 ('Monika', 59),
 ('Mehul', 55),
 ('Aradhana', 54),
 ('Ayushi', 46),
 ('Raksha', 43),
 ('Jagriti', 42),
 ('Vishal', 41),
 ('Anjali', 32),
 ('Ajaz', 31),
 ('Jayanti', 31),
 ('Sajia', 29),
 ('Niharika', 14),
 ('Deepak', 5),
 ('Argha', 1)]